---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: cloudlog-docker-build-
spec:
  serviceAccountName: zcashsysadmin-service
  taskRef:
    name: build-docker-image-from-git-source
  inputs:
    resources:
      - name: docker-source
        resourceSpec:
          type: git
          params:
            - name: revision
              value: master
            - name: url
              value: https://github.com/zcash-hackworks/cloudlog.git
    params:
      - name: pathToDockerFile
        value: /workspace/docker-source/Dockerfile
      - name: pathToContext
        value: /workspace/docker-source/
  outputs:
    resources:
      - name: builtImage
        resourceSpec:
          type: image
          params:
            - name: url
              value: electriccoinco/cloudlog
      - name: notification
        resourceRef:
          name: event-to-cloudlog