---
kind: Service
apiVersion: v1
metadata:
  name: cloudlog
  labels:
    app: cloudlog
spec:
  type: NodePort
  selector:
    app: cloudlog
  ports:
  - name: cloudlog
    protocol: TCP
    port: 3000
